import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, currentUser } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";
import Bottombar from "@/components/shared/Bottombar";
import Topbar from "@/components/shared/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prisha Books",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <head>
          <link
            rel="shortcut icon"
            href="https://prishapolicy.com/favicon.png"
            type="image/x-icon"
          />
        </head>
        <body className={inter.className}>
          <Topbar />

          <main className="flex flex-row">
            <section className="main-container">
              <div className="w-full">{children}</div>
            </section>
          </main>

          <Bottombar userId={user?.id || ""} />
        </body>
      </html>
    </ClerkProvider>
  );
}
